JanitorTechnology/dockerfiles

firefox/mozconfig
Both improvements were suggested by @luser on Mozilla's #ateam IRC channel. Thanks Ted!
=> Improve default Firefox mozconfig options

ubuntu-dev/ubuntu-dev.dockerfile
Simple change, merging without review.
=> [ubuntu-dev] install arc for all images

ubuntu-dev/ubuntu-dev.dockerfile
Upgrade all project images to Node.js 8.0.0 ([announcement](https://nodejs.org/en/blog/release/v8.0.0/)) and npm 5.0.0 ([announcement](http://blog.npmjs.org/post/161276872334/npm5-is-now-npmlatest)).
=> [ubuntu-dev] upgrade to node 8.0.0 and npm 5.0.0

firefox/firefox.dockerfile, janitor/janitor-update.dockerfile, thunderbird/thunderbird.dockerfile, ubuntu-dev/supervisord.conf, ubuntu-dev/ubuntu-dev.dockerfile
It's my fault, I merged things without actually testing them, so the recent image updates came with several subtle breakages.
=> Minor fixes

ubuntu-dev/client-workspace-janitor.js, ubuntu-dev/supervisord.conf, ubuntu-dev/ubuntu-dev.dockerfile
Let's improve this commit somewhat, and wait for https://github.com/nt1m/c9.ide.reviewcomments/issues/2 to be fixed before merging.
=> [ubuntu-dev] install nt1m's cloud9 plugin for review comments

.circleci/config.yml
=> [all] fix circleci workflow configuration

ubuntu-dev/ubuntu-dev.dockerfile
Requested by @paulrouget (thanks for the suggestion!)
=> [ubuntu-dev] install tmux for all images

chromium/chromium.dockerfile, chromium/janitor.json
=> [chromium] fix running without the SETUID sandbox

ubuntu-dev/workspace-janitor.js
This is a follow-up to https://github.com/JanitorTechnology/janitor/pull/169
=> Change Dashboard URL new containers directory

ubuntu-dev/ubuntu-dev.dockerfile
=> [ubuntu-dev] don't install pip3, it breaks ubuntu 16.04

discourse/discourse.dockerfile
Together with some tweaks to Janitor's proxy, this should fix our 404 errors.
=> Add the relative URL root to Discourse

discourse/discourse.dockerfile
=> Put newlines between commands in bashrc

servo/servo.dockerfile
=> [servo] update package dependency list

discourse/discourse.dockerfile, discourse/janitor.json
Reverts JanitorTechnology/dockerfiles#108
=> Revert "Add the relative URL root to Discourse"

discourse/janitor.json
https://github.com/JanitorTechnology/c9.ide.janitorconfig/pull/9
=> Mark the Discourse port number as the preview port

discourse/janitor.json
I'm not sure if this is better, or if running one or both of these under supervisord would be better.
=> Add MailCatcher and Sidekiq buttons

chromium/chromium.dockerfile
`git cl` completion would be nice: https://chromium.googlesource.com/chromium/tools/depot_tools/+/HEAD/README.git-cl.md
This CL also fixes nits in docker file.
=> Add git cl completion and fix docker nits

chromium/chromium.dockerfile
FIX https://github.com/JanitorTechnology/dockerfiles/issues/143
=> Removed not supported Heredoc

fennec/fennec.dockerfile, fennec/janitor.json, fennec/mozconfig, ubuntu-dev/ubuntu-dev.dockerfile
I spent a few hours writing this Dockerfile, and tested its build almost all the way through (now it's Circle CI's job to take it to completion).
@nt1m please have a look 😄 especially regarding which software versions/tools I install (Android SDK and Simulator aren't yet part of the image), and the workflow scripts I added to `janitor.json`.
Thanks!
=> Add Firefox for Android

chromium/chromium.dockerfile, fennec/fennec.dockerfile, fennec/mozconfig, thunderbird/thunderbird.dockerfile, ubuntu-dev/ubuntu-dev.dockerfile
Attempting to work around #151.
=> [fennec] attempt to link with lld instead of gold

fennec/fennec.dockerfile, fennec/mozconfig
Thanks a lot to @ncalexan for helping me with this on IRC!
=> [fennec] bootstrap with `android.py --no-interactive`; switch to i386 emulator; fix build

ubuntu-dev/ubuntu-dev.dockerfile
For DSpace and Firefox for Android.
=> Add default-jdk to ubuntu-dev

chromium/chromium.dockerfile, chromium/janitor.json, discourse/discourse.dockerfile, discourse/janitor.json, dspace/dspace.dockerfile, dspace/janitor.json, fennec/fennec.dockerfile, fennec/janitor.json, firefox/firefox-git.dockerfile, firefox/firefox-hg.dockerfile, janitor/janitor.dockerfile, rust/janitor.json, rust/rust.dockerfile, servo/janitor.json, servo/servo.dockerfile, thunderbird/janitor.json, thunderbird/thunderbird.dockerfile, ubuntu-dev/supervisord.conf, ubuntu-dev/theia/package.json, ubuntu-dev/theia/settings.json, ubuntu-dev/ubuntu-dev.dockerfile
Also did some refactoring to the workspace directory mechanism, so we can just edit an environment variable instead of long sed expression.
Briefly tested.
=> Install the Theia IDE

dspace/environment.prod.js
This PR adds the required environment.prod.js file modified to make DSpace-Angular compatible with Janitor.
=> Add environment.prod.js to dspace

ubuntu-dev/ubuntu-dev.dockerfile
... which also fixes git prompt.
=> [ubuntu-dev] Add bash-completion

ubuntu-dev/ubuntu-dev.dockerfile
=> [ubuntu-dev] install the latest gcc-6 for all images

ubuntu-dev/ubuntu-dev.dockerfile
=> Use clippy from master

ubuntu-dev/ubuntu-dev.dockerfile
This cleans up Rust component installation.
=> rustup components cleanup

servo/servo.dockerfile
Fixes https://github.com/JanitorTechnology/janitor/issues/345
=> [servo] fix image build by setting HARFBUZZ_SYS_NO_PKG_CONFIG=1

thunderbird/.mozconfig, thunderbird/janitor.json, thunderbird/thunderbird-update.dockerfile, thunderbird/thunderbird.dockerfile
=> [thunderbird] update images to use new source layout.

discourse/discourse.dockerfile
https://github.com/discourse/discourse_theme
https://meta.discourse.org/t/discourse-theme-cli-console-app-to-help-you-build-themes/82950
=> Install the Discourse Theme CLI by default

servo/servo.dockerfile, ubuntu-dev/ubuntu-dev.dockerfile
Various image builds are currently broken in CircleCI:
Hopefully this should unbreak most of them, and produce much fresher + nicer environments to code in.
=> Big updates to most dockerfiles

firefox/firefox-cinnabar.dockerfile, firefox/firefox-git.dockerfile
=> [firefox-git] also install moz-phab because the docs recommend it

servo/servo.dockerfile
Attempting to fix https://discourse.janitor.technology/t/how-to-rebuild-a-project/250
=> [servo] don't manually pre-install libgstreamer
