JanitorTechnology/dockerfiles

thunderbird.docker

Mostly copied from firefox.docker, but removed moz-git-tools because Thunderbird folks usually use hg and I'm not sure we even have a git copy of the comm- repositories. I've tested this locally, and while my disk ran out of space in the very last moment, I did see the final build messages so I think it will work this way.

[thunderbird] build and run thunderbird with lightning

---

janitor/db.json
janitor/janitor.dockerfile
readme.md

This should allow us to [Put The Janitor in The Janitor](https://github.com/JanitorTechnology/janitor/issues/31) 🎉🎈🍕🍾
Not tested yet, and to work properly out-of-the-box it also depends on an upcoming Janitor commit (titled "Allow forcing insecure HTTP for local development only").

Add development Dockerfile for Janitor

---

ubuntu-dev/ubuntu-dev.dockerfile

This is a temporary workaround for https://public-inbox.org/git/CAA6PgK74CTT09RZiQWGoih3x6B5G4tLa_Vz7e9BDNW4+TGdLXw@mail.gmail.com/

[ubuntu-dev] fix circleci by temporarily disabling git profile builds

---

ubuntu-dev/ubuntu-dev.dockerfile

The Chromium build currently fails on CircleCI, and it shows this error:
> Installing locales.
> sudo: locale-gen: command not found
> The command '/bin/sh -c echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections  && sudo src/build/install-build-deps.sh --no-prompt --no-arm --no-chromeos-fonts --no-nacl' returned a non-zero code: 1
> Exited with code 1
I believe that simply installing the Ubuntu package `locales` will fix that.

[ubuntu-dev] install locales for all images

---

.circleci/config.yml
ubuntu-dev/ubuntu-dev.dockerfile

This change makes CircleCI pull all Docker images from Docker Hub before re-building them in order to re-use their cached layers where possible. This should make image updates both faster and smaller.
Another option would be to cache image layers locally in CircleCI, as shown in this [blog post](https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/#build-and-cache-docker-images).

[all] use docker layer cache to optimize circleci builds

---

.circleci/config.yml
janitor/janitor-update.dockerfile
readme.md

Docker Hub automated builds are easier to set up, and seem to be more useful for small projects like Janitor.
You just need to go to Docker Hub, create a new "automated build", point it to your repository and dockerfile, and voilà. (Additionally, you can set it up to also rebuild on pushes to other images, e.g. `janx/ubuntu-dev`.)
I think this could become the official way to add new projects to Janitor.

[janitor] use docker hub automated builds instead of circleci

---

.circleci/config.yml

Using the default tag `:latest` for all our images will be more convenient for Docker users than our custom `:base` tag from before.
Also, https://github.com/JanitorTechnology/janitor/commit/32453b7f47d1a07748ef800e6a9ff40ffba545ba should allow Janitor to support these images (because it stopped Janitor from using the default tag `:latest` itself internally. It now uses `:janitor-production`).

[chromium][firefox][servo][thunderbird] tag docker images with :latest instead of :base on circleci and docker hub

---

.circleci/config.yml
ubuntu-dev/workspace-janitor.js

In this pull request, I increase the default code editor font size in Cloud9 SDK from 12 to 14 (it's more comfortable for coding, and still shows a lot of code even on small screens. It's the font size already used in the Terminal).
I also wanted to change the default indentation from 4 to 2, and to enable "remove trailing spaces on save" by default, but I couldn't find these settings in `p.settings.user`. Maybe they're elsewhere?
Also: I sneak in a change in Chromium's `no_output_timeout` variable, in an attempt to work around the 5 hours build limit on CircleCI. Fingers crossed.

[ubuntu-dev] increase c9sdk code editor font size to 14

---

ubuntu-dev/supervisord.conf

More details on `--useBrowserCache` feature in this [Cloud9 SDK email thread](https://groups.google.com/forum/#!topic/cloud9-sdk/F-ksHqHhMUM).

[ubuntu-dev] enable c9sdk browser caching for all images

---

ubuntu-dev/ubuntu-dev.dockerfile

This is terrible. Please suggest a better solution if you know one.

[ubuntu-dev] force pip to use python 2.7 and not python 3+

---

discourse/discourse-update.dockerfile
discourse/discourse.dockerfile
discourse/janitor.json
discourse/supervisord-append.conf

This is used by <https://discourse.janitor.technology/>, and can act as the staging environment for tweaks to the Janitor Community forum.

Add a development environment for Discourse

---

chromium/janitor.json
firefox/janitor-git.json
firefox/janitor-hg.json
servo/janitor.json
thunderbird/janitor.json

Now that we repeat explicit commands between `()` in c9runner names, we can make the actual script names more descriptive.

[chromium][firefox][servo][thunderbird] tweak janitor.json scripts

---

chromium/chromium.dockerfile

It turns out WORKDIR executes commands as `root`. Since we we need to create a `.gclient` file later, we need to use `RUN mkdir` before.
An alternative would be to change user to `root`.
R: @jankeromnes

Re-add mkdir command to fix permission issue

---

.circleci/config.yml
readme.md

A follow-up to #146 that adds Fennec to our Circle CI manifest in order to automate its build & deployment.

[fennec] automatically build and push docker image with circleci

---

.circleci/config.yml

Follow-up to #147, where I added a `fennec` Circle CI job, but forgot to add it to the `build-and-deploy` automated workflow.

[fennec] automatically build and push docker image with circleci 2/2

---

ubuntu-dev/ubuntu-dev.dockerfile

It may be unacceptable for pure JS project to have TS as a devDependency, so we should have a fallback in the case.

[ubuntu-dev] Install typescript globally

---

.circleci/build_image.sh

- We enable set -x so do not reference any variable directly. Heredoc doesn't subject to trace, but maybe we want to turn it off entirely when logging in.
- CIRCLE_PULL_REQUEST is a URL and is not suitable for a Docker Hub tag. Doing it doesn't make sense anyway.
* If you still want this, use CIRCLE_PR_NUMBER instead.
@jankeromnes rotate your password.

Fix CI tagging and credential exposure

---

chromium/chromium-update.dockerfile
chromium/chromium.dockerfile
discourse/discourse.dockerfile
dspace/dspace.dockerfile
fennec/fennec.dockerfile
firefox/firefox-git.dockerfile
firefox/firefox-hg.dockerfile
servo/servo.dockerfile
thunderbird/thunderbird.dockerfile
ubuntu-dev/ubuntu-dev.dockerfile

asciidoc drags in the whole texlive suite, which weighs at about 500MB. apt repositories should be also cleaned, while the impact is not large.

ubuntu-dev: reduce bloat

---

ubuntu-dev/theia/package.json

This extension seems to have different release cycle and probably has posed compatibility issues. Removing allowed Theia to boot.

Fix Theia incompatibility

---

chromium/chromium.dockerfile

With this preset build is 3x faster (3h -> 1h) and artifacts takes 1/4 space (26GiB -> 6GiB).
Jumbo: in general this is good for build speed. Slightly makes rebuild slower.
Reduced debug level: the debug information is function only as opposed to line-level. This may make debug harder but in general it's not a critical drawback.
Documents: https://chromium.googlesource.com/chromium/src/+/lkcr/docs/linux_build_instructions.md#faster-builds

Chromium: use a faster preset

---

fennec/mozconfig

Unofficial builds use something like `fennec_${USER}` as the package name, and apparently
this causes us to use an invalid package name. Re-enabling official branding should fix it.

[fennec] fix build by re-enabling official branding

---

ubuntu-dev/supervisord.conf

In some containers x11vnc stays alive for just over a second and then dies.
Repeatedly. This fix should save us a lot of unnecessary compute and logs.

 [ubuntu-dev] bump supervisor startsecs from 1 to 5 for fragile x11vnc process
